version: '3.7'

services:
  server:
    image: "xehesi/hashcash-server:latest"
    platform: linux/amd64
    environment:
      LOG_LEVEL: "debug"
      SERVER_ADDR: "0.0.0.0:8080"
    ports:
      - "8080:8080"
    networks:
      - hashcash

  client:
    image: "xehesi/hashcash-client:latest"
    platform: linux/amd64
    environment:
      LOG_LEVEL: "debug"
      SERVER_ADDR: "server:8080"
    networks:
      - hashcash
    depends_on:
      - server

  client-ddos:
    image: "xehesi/hashcash-client:latest"
    platform: linux/amd64
    environment:
      LOG_LEVEL: "debug"
      SERVER_ADDR: "server:8080"
      CLIENT_DDOS_MODE: "true"
    networks:
      - hashcash
    depends_on:
      - server

networks:
  hashcash:

