name: build & release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-tools:
    runs-on: ubuntu-latest
    name: Setup cache
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-

  test:
    needs: build-tools
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...

  build:
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-

      - name: Build server
        run: go build -o dist/server ./cmd/server

      - name: Build client
        run: go build -o dist/client ./cmd/client

      - name: Upload assets
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: hashcash-
          path: dist/*

  docker-push:
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build/Push server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployments/docker/client/Dockerfile
          push: true
          tags: |
            xehesi/hashcash-server:latest

      - name: Build/Push cli
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployments/docker/server/Dockerfile
          push: true
          tags: |
            xehesi/hashcash-client:latest
